apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcbqc-web
  namespace: pcbqc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcbqc-web
  template:
    metadata:
      labels:
        app: pcbqc-web
    spec:
      containers:
        - name: web
          image: acrpcbqc19589.azurecr.io/pcbqc/web:4ce1d2b
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          env:
            # Make Ultralytics writable
            - name: YOLO_CONFIG_DIR
              value: /tmp/Ultralytics

          volumeMounts:
            - name: ultralytics-tmp
              mountPath: /tmp/Ultralytics

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20

      volumes:
        - name: ultralytics-tmp
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: pcbqc-web-svc
  namespace: pcbqc
spec:
  selector:
    app: pcbqc-web
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP

