apiVersion: amlarc.azureml.com/v1alpha1
kind: InstanceType
metadata:
  name: cpu2-6g
spec:
  resources:
    requests:
      cpu: "500m"
      memory: "4Gi"
    limits:
      cpu: "2"
      memory: "6Gi"
